name: babylon-api

services:
  babylon.alfred.api:
    image: babylon.alfred.api
    build:
      context: ../..
      dockerfile: src/Babylon.Alfred/Babylon.Alfred.Api/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
    ports:
      - "8000:8080"

  babylon.alfred.worker:
    image: babylon.alfred.worker
    build:
      context: ../..
      dockerfile: src/Babylon.Alfred/Babylon.Alfred.Worker/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
