name: babylon-api
services:
  # postgres:
  #   image: postgres:16-alpine
  #   container_name: babylon_postgres
  #   environment:
  #     POSTGRES_DB: babylon_dev
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U postgres"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5

  babylon.alfred.api:
    image: babylon.alfred.api
    build:
      context: .
      dockerfile: Babylon.Alfred.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
#      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=babylon_dev;Username=postgres;Password=postgres
    ports:
      - "8000:8080"
    # depends_on:
    #   postgres:
    #     condition: service_healthy

  babylon.alfred.worker:
    image: babylon.alfred.worker
    build:
      context: .
      dockerfile: Babylon.Alfred.Worker/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
#      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=babylon_dev;Username=postgres;Password=postgres
    # depends_on:
    #   postgres:
    #     condition: service_healthy

volumes:
  postgres_data:
